import jsPDF from 'jspdf';
import 'jspdf-autotable';
import type { RuleViolation, ViolationStatus } from '@/types/emergency-validation';

// Declare jsPDF autoTable plugin
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: {
      finalY: number;
    };
  }
}

interface ReportOptions {
  violations: RuleViolation[];
  filter?: ViolationStatus | 'all';
  generatedBy?: string;
}

export function generateViolationReport({
  violations,
  filter = 'all',
  generatedBy = 'Admin Dashboard',
}: ReportOptions) {
  const doc = new jsPDF();
  
  // Filter violations
  const filteredViolations = filter === 'all' 
    ? violations 
    : violations.filter(v => v.status === filter);

  // Sort by timestamp (newest first)
  const sortedViolations = [...filteredViolations].sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
  );

  // Colors
  const primaryColor = [59, 130, 246]; // Blue
  const darkColor = [31, 41, 55]; // Dark gray
  const lightGray = [243, 244, 246];
  const redColor = [239, 68, 68];
  const greenColor = [34, 197, 94];
  const yellowColor = [234, 179, 8];

  // ==================== HEADER ====================
  // Company/Project name
  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246); // Blue
  doc.setFont('helvetica', 'bold');
  doc.text('Smart Traffic Signal System', 105, 20, { align: 'center' });

  // Report title
  doc.setFontSize(18);
  doc.setTextColor(31, 41, 55); // Dark gray
  doc.text('Violation Report', 105, 30, { align: 'center' });

  // Divider line
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);

  // ==================== REPORT INFO ====================
  doc.setFontSize(10);
  doc.setTextColor(31, 41, 55);
  doc.setFont('helvetica', 'normal');

  const reportDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  doc.text(`Generated: ${reportDate}`, 20, 43);
  doc.text(`Generated By: ${generatedBy}`, 20, 50);
  doc.text(`Total Violations: ${sortedViolations.length}`, 20, 57);
  doc.text(`Filter: ${filter === 'all' ? 'All Statuses' : filter}`, 20, 64);

  // ==================== SUMMARY STATISTICS ====================
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(59, 130, 246); // Blue
  doc.text('Summary Statistics', 20, 76);

  const stats = {
    total: sortedViolations.length,
    pending: sortedViolations.filter(v => v.status === 'PENDING').length,
    validated: sortedViolations.filter(v => v.status === 'VALIDATED').length,
    misuse: sortedViolations.filter(v => v.status === 'MISUSE').length,
    conditional: sortedViolations.filter(v => v.status === 'CONDITIONAL_PENDING').length,
    overspeed: sortedViolations.filter(v => v.type === 'OVERSPEED').length,
    signalBreak: sortedViolations.filter(v => v.type === 'SIGNAL_BREAK').length,
    emergencyMode: sortedViolations.filter(v => v.emergencyModeActive).length,
  };

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(31, 41, 55); // Dark gray

  let yPosition = 84;
  doc.text(`By Status:`, 20, yPosition);
  yPosition += 7;
  doc.text(`  • Pending: ${stats.pending}`, 25, yPosition);
  yPosition += 6;
  doc.text(`  • Validated: ${stats.validated}`, 25, yPosition);
  yPosition += 6;
  doc.text(`  • Misuse: ${stats.misuse}`, 25, yPosition);
  yPosition += 6;
  doc.text(`  • Conditional Pending: ${stats.conditional}`, 25, yPosition);
  yPosition += 8;

  doc.text(`By Type:`, 20, yPosition);
  yPosition += 7;
  doc.text(`  • Overspeed: ${stats.overspeed}`, 25, yPosition);
  yPosition += 6;
  doc.text(`  • Signal Break: ${stats.signalBreak}`, 25, yPosition);
  yPosition += 8;

  doc.text(`Emergency Mode Violations: ${stats.emergencyMode}`, 20, yPosition);
  yPosition += 10;

  // ==================== VIOLATIONS TABLE ====================
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(59, 130, 246); // Blue
  doc.text('Violation Details', 20, yPosition);
  yPosition += 5;

  // Prepare table data
  const tableData = sortedViolations.map((v, index) => {
    const date = new Date(v.timestamp);
    const formattedDate = date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
    const formattedTime = date.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
    });

    return [
      index + 1,
      v.driverName,
      v.vehicleNumber,
      v.type === 'OVERSPEED' ? 'Overspeed' : v.type === 'SIGNAL_BREAK' ? 'Signal Break' : 'Unauthorized',
      `${v.speedAtViolation} km/h`,
      `${v.speedLimit} km/h`,
      v.emergencyModeActive ? 'Yes' : 'No',
      v.status.replace('_', ' '),
      `${formattedDate}\n${formattedTime}`,
    ];
  });

  // Create table
  doc.autoTable({
    startY: yPosition,
    head: [['#', 'Driver', 'Vehicle', 'Type', 'Speed', 'Limit', 'Emergency', 'Status', 'Date/Time']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: 3,
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2,
    },
    alternateRowStyles: {
      fillColor: lightGray,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 25 },
      2: { cellWidth: 25 },
      3: { cellWidth: 20 },
      4: { cellWidth: 18, halign: 'center' },
      5: { cellWidth: 18, halign: 'center' },
      6: { cellWidth: 18, halign: 'center' },
      7: { cellWidth: 25, halign: 'center' },
      8: { cellWidth: 25 },
    },
    didParseCell: function (data) {
      // Color code status column
      if (data.section === 'body' && data.column.index === 7) {
        const status = data.cell.raw as string;
        if (status === 'VALIDATED') {
          data.cell.styles.textColor = greenColor;
          data.cell.styles.fontStyle = 'bold';
        } else if (status === 'MISUSE') {
          data.cell.styles.textColor = redColor;
          data.cell.styles.fontStyle = 'bold';
        } else if (status === 'PENDING') {
          data.cell.styles.textColor = yellowColor;
          data.cell.styles.fontStyle = 'bold';
        }
      }
    },
    margin: { left: 20, right: 20 },
  });

  // ==================== FOOTER ====================
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.setFont('helvetica', 'normal');
    
    // Footer text
    doc.text(
      `Page ${i} of ${pageCount} | Smart Traffic Signal System - Violation Report`,
      105,
      290,
      { align: 'center' }
    );
    
    // Confidential notice
    doc.setFontSize(7);
    doc.text(
      'CONFIDENTIAL: This report contains sensitive traffic violation data. Handle with care.',
      105,
      295,
      { align: 'center' }
    );
  }

  // ==================== SAVE PDF ====================
  const filename = `Violation_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
  
  return filename;
}
